GET /api/event

###
GET /api/event/64d3909aa038e9217bcf9b85

###
GET http://localhost:5173/api/event/flagstaff

### 
POST /api/event
Content-Type: application/json

{
    "join": "true",
    "time": "12.00pm",
    "location": {"street": "La Trobe Street", "city": "Melbourne"},
    "eventType": "test",
    "comment": [{"user": "boo", "comment": "test"}]
}

###
PATCH /api/event/64d3909aa038e9217bcf9b85
Content-Type: application/json

{
    "join": "true",
    "time": "4.00pm",
    "location": {"street": "La Trobe Street", "city": "Melbourne"},
    "eventType": "test2",
    "comment": [{"user": "booboo", "comment": "test"}]
}

###
DELETE http://localhost:3000/api/event/64d3909aa038e9217bcf9b85

###
POST http://localhost:3000/api/register/
Content-Type: application/json

{
    "name": "Garnie",
    "email": "garnie@test.com",
    "password": "09876543",
    "DOB": "1985-12-20",
    "location": "Melbourne"
}

###
POST http://localhost:3000/api/comment/
Content-Type: application/json

{
    "eventID": "64db7f39d5fa513db7be73d1",
    "userID": "64d6cf0ae2d7d298aee3a7bf",
    "username": "Garnie",
    "comment": "Sounds good! Def will join"
}

###
GET http://localhost:3000/api/comment/64db7f39d5fa513db7be73d1

###
PATCH http://localhost:3000/api/comment/64dccf38bd8951fefb3426e1
Content-Type: application/json

{
    "comment": "For sure!"
}

###
DELETE http://localhost:3000/api/comment/64dccb2532a43ec1fa961a38
