GET /api/event

###
GET /api/event/64d3909aa038e9217bcf9b85

###
GET http://localhost:5173/api/event/flagstaff

### 
POST /api/event
Content-Type: application/json

{
    "join": "true",
    "time": "12.00pm",
    "location": {"street": "La Trobe Street", "city": "Melbourne"},
    "eventType": "test",
    "comment": [{"user": "boo", "comment": "test"}]
}

###
PATCH /api/event/64d3909aa038e9217bcf9b85
Content-Type: application/json

{
    "join": "true",
    "time": "4.00pm",
    "location": {"street": "La Trobe Street", "city": "Melbourne"},
    "eventType": "test2",
    "comment": [{"user": "booboo", "comment": "test"}]
}

###
DELETE http://localhost:3000/api/event/64d3909aa038e9217bcf9b85

###
POST http://localhost:3000/api/register/
Content-Type: application/json

{
    "name": "Garnie",
    "email": "garnie@test.com",
    "password": "09876543",
    "DOB": "1985-12-20",
    "location": "Melbourne"
}
